$\newcommand{\xv}{\mathbf{x}}
\newcommand{\Xv}{\mathbf{X}}
\newcommand{\yv}{\mathbf{y}}
\newcommand{\zv}{\mathbf{z}}
\newcommand{\av}{\mathbf{a}}
\newcommand{\Wv}{\mathbf{W}}
\newcommand{\wv}{\mathbf{w}}
\newcommand{\tv}{\mathbf{t}}
\newcommand{\Tv}{\mathbf{T}}
\newcommand{\muv}{\boldsymbol{\mu}}
\newcommand{\sigmav}{\boldsymbol{\sigma}}
\newcommand{\phiv}{\boldsymbol{\phi}}
\newcommand{\Phiv}{\boldsymbol{\Phi}}
\newcommand{\Sigmav}{\boldsymbol{\Sigma}}
\newcommand{\Lambdav}{\boldsymbol{\Lambda}}
\newcommand{\half}{\frac{1}{2}}
\newcommand{\argmax}[1]{\underset{#1}{\operatorname{argmax}}}
\newcommand{\argmin}[1]{\underset{#1}{\operatorname{argmin}}}$

# Assignment 6: Neural Networks

*Sean Russell*

## Overview

You will write and apply code that trains neural networks of various numbers of hidden layers and units in each hidden layer and returns results as specified below.  You will do this once for a regression problem and once for a classification problem. 

## Required Code

Download [nn2.tar](http://www.cs.colostate.edu/~anderson/cs440/notebooks/nn2.tar) that was used in lecture and extract its contents, which are

* `neuralnetworks.py`
* `scaledconjugategradient.py`
* `mlutils.py`

Write the following functions that train and evaluate neural network models.

* `results = trainNNs(X, T, trainFraction, hiddenLayerStructures, numberRepetitions, numberIterations, classify)`

The arguments to `trainNNs` are

* `X` is a matrix of input data of shape `nSamples x nFeatures`
* `T` is a matrix of target data of shape `nSamples x nOutputs`
* `trainFraction` is fraction of samples to use as training data. 1-`trainFraction` is number of samples for testing data
* `hiddenLayerStructures` is list of network architectures. For example, to test two networks, one with one hidden layer of 20 units, and one with 3 hidden layers with 5, 10, and 20 units in each layer, this argument would be `[[20], [5, 10, 20]]`.
* `numberRepetitions` is number of times to train a neural network.  Calculate training and testing average performance (two separate averages) of this many training runs.
* `numberIterations` is the number of iterations to run the scaled conjugate gradient algorithm when a neural network is trained.
* `classify` is set to `True` if you are doing a classification problem, in which case `T` must be a single column of target class integers.

This function returns `results` which is list with one element for each network structure tested.  Each element is a list containing 

* the hidden layer structure (as a list),
* a list of training data performance for each repetition, 
* a list of testing data performance for each repetition, and
* the number of seconds it took to run this many repetitions for this network structure.

This function should follow these steps:

  * For each network structure given in `hiddenLayerStructures`
    * For numberRepetitions
      * Use `ml.partition` to randomly partition X and T into training and testing sets.
      * Create a neural network of the given structure
      * Train it for numberIterations
      * Use the trained network to produce outputs for the training and for the testing sets
      * If classifying, calculate the fraction of samples incorrectly classified for training and testing sets.
       Otherwise, calculate the RMSE of training and testing sets.
      * Add the training and testing performance to a collection (such as a list) for this network structure
    * Add to a collection of all results the hidden layer structure, lists of training performance and testing performance, and seconds taken to do these repetitions.
  * return the collection of all results

Also write the following two functions. `summarize(results)` returns a list of lists like `results` but with the list of training performances replaced by their mean and the list of testing performances replaced by their mean.   
`bestNetwork(summary)` takes the output of `summarize(results)` and returns the best element of `results`, determined by the element that has the smallest test performance.

* `summary = summarize(results)` where `results` is returned by `trainNNs` and `summary` is like `results` with the training and testing performance lists replaced by their means
* `best = bestNetwork(summary)` where `summary` is returned by `summarize` and `best` is the best element of `summary`

Just a bunch of imports

In [4]:
import numpy as np
import mlutils as ml
import neuralnetworks as nn
import time
from sklearn.metrics import mean_squared_error
from math import sqrt
import copy
import pandas as pd

Heres the meat of the code. trainNNs trains and tests a bunch of networks all at once with different hidden layer structures and returns the performance of each different network structure. summarize takes these results and makes them a bit easier to read, and bestNetwork takes the summary and only returns the results for the best network structure.

In [5]:
def trainNNs(X, T, trainFraction, hiddenLayerStructures, numberRepetitions, numberIterations, classify=False):
    results = []
    for structure in hiddenLayerStructures:
        result = []
        trainingPerformance = []
        testingPerformance = []
        result.append(structure)
        startTime = time.time()
        for n in range(numberRepetitions):
            trainX, trainT, testX, testT = ml.partition(X,T,[trainFraction,1-trainFraction],classify)
            model = nn.NeuralNetworkClassifier(X.shape[1],structure,len(np.unique(T))) if classify else nn.NeuralNetwork(X.shape[1],structure,T.shape[1])
            model.train(trainX, trainT, numberIterations)
            predictedTrain = model.use(trainX)
            predictedTest = model.use(testX)
            RMSE = lambda actual, predicted: sqrt(mean_squared_error(actual, predicted))
            trainError = 1 - ml.percentCorrect(predictedTrain,trainT) / 100 if classify else RMSE(trainT, predictedTrain)
            testError = 1 - ml.percentCorrect(predictedTest,testT) / 100 if classify else RMSE(testT, predictedTest)
            trainingPerformance.append(trainError)
            testingPerformance.append(testError)
        endTime = time.time()
        result.append(trainingPerformance)
        result.append(testingPerformance)
        result.append(endTime - startTime)
        results.append(result)  
    return results

def summarize(results):
    results = copy.deepcopy(results)
    for result in results:
        result[1] = sum(result[1]) / len(result[1])
        result[2] = sum(result[2]) / len(result[2])
    return results

def bestNetwork(summary):
    bestResult = summary[0]
    for result in summary:
        if result[2] < bestResult[2]:
            bestResult = result
    return bestResult

## Data for Regression Experiment

From the UCI Machine Learning Repository, download the [Appliances energy prediction](http://archive.ics.uci.edu/ml/datasets/Appliances+energy+prediction) data.  You can do this by visiting the Data Folder for this data set, or just do this:

     !wget http://archive.ics.uci.edu/ml/machine-learning-databases/00374/energydata_complete.csv



Read this data into python.  One suggestion is to use the `loadtxt` function in the `numpy` package.  You may ignore the first column of each row which contains a data and time.  Also ignore the last two columns of random variables.  We will not use that in our modeling of this data.  You will also have to deal with the double quotes that surround every value in every field.  Read the first line of this file to get the names of the features.

Once you have read this in correctly, you should see values like this:

In [7]:
def readData(fileName, excludedColumns):
    df = pd.read_csv(fileName)
    for excluded in excludedColumns:
        df.drop(excluded, axis=1, inplace = True)
    return df

In [8]:
fileName = 'energydata_complete.csv'
excludedColumns = ['date', 'rv1', 'rv2']
df = readData(fileName, excludedColumns)
names = list(df.axes[1])
data = df.as_matrix()
Xenergy = data[:,2:]
Tenergy = data[:,:2]
Xnames = names[2:]
Tnames = names[:2]

Train several neural networks on all of this data for 100 iterations.  Plot the error trace (nnet.getErrorTrace()) to help you decide now many iterations might be needed.  100 may not be enough.  If for your larger networks the error is still decreasing after 100 iterations you should train all nets for more than 100 iterations.

Now use your `trainNNs`, `summarize`, and `bestNetwork` functions on this data to investigate various network sizes.

In [125]:
results = trainNNs(Xenergy, Tenergy, 0.8, [0, 5, [5, 5], [10, 10]], 10, 100)

In [126]:
summarize(results)

[[0, 67.14380511599147, 67.26430089723117, 2.2673590183258057],
 [5, 65.27477821593422, 65.585980240998, 23.882287979125977],
 [[5, 5], 64.87599148368307, 66.06982609562651, 35.216299057006836],
 [[10, 10], 62.90730436756324, 64.00417527576994, 58.27176809310913]]

In [127]:
bestNetwork(summarize(results))

[[10, 10], 62.90730436756324, 64.00417527576994, 58.27176809310913]

Test at least 10 different hidden layer structures.  Larger numbers of layers and units may do the best on training data, but not on testing data. Why?

Now train another network with your best hidden layer structure on 0.8 of the data and use the trained network on the testing data (the remaining 0.2 of the date).  As before use `ml.partition` to produce the training and testing sets.

For the testing data, plot the predicted and actual `Appliances` energy use, and the predicted and actual `lights` energy use, in two separate plots.  Discuss what you see.

## Data for Classification Experiment

From the UCI Machine Learning Repository, download the [Anuran Calls (MFCCs)](http://archive.ics.uci.edu/ml/datasets/Anuran+Calls+%28MFCCs%29) data.  You can do this by visiting the Data Folder for this data set, or just do this:

     !wget 'http://archive.ics.uci.edu/ml/machine-learning-databases/00406/Anuran Calls (MFCCs).zip'
     !unzip Anuran*zip
     
Read the data in the file `Frogs_MFCCs.csv` into python.  This will be a little tricky. Each line of the file is a sample of audio features plus three columns that label the sample by family, genus, and species. We will try to predict the species.  The tricky part is that the species is given as text.  We need to convert this to a target class, as an integer. The `numpy` function `unique` will come in handy here.

In [205]:
df = pd.read_csv('Frogs_MFCCs.csv')
exclude = ['Family', 'Genus', 'RecordID']
for excluded in exclude:
    df.drop(excluded, axis=1, inplace = True)
df

MFCCs_ 1  MFCCs_ 2  MFCCs_ 3  MFCCs_ 4  MFCCs_ 5  MFCCs_ 6  MFCCs_ 7  \
0          1.0  0.152936 -0.105586  0.200722  0.317201  0.260764  0.100945   
1          1.0  0.171534 -0.098975  0.268425  0.338672  0.268353  0.060835   
2          1.0  0.152317 -0.082973  0.287128  0.276014  0.189867  0.008714   
3          1.0  0.224392  0.118985  0.329432  0.372088  0.361005  0.015501   
4          1.0  0.087817 -0.068345  0.306967  0.330923  0.249144  0.006884   
5          1.0  0.099704 -0.033408  0.349895  0.344535  0.247569  0.022407   
6          1.0  0.021676 -0.062075  0.318229  0.380439  0.179043 -0.041667   
7          1.0  0.145130 -0.033660  0.284166  0.279537  0.175211  0.005791   
8          1.0  0.271326  0.027777  0.375738  0.385432  0.272457  0.098192   
9          1.0  0.120565 -0.107235  0.316555  0.364437  0.307757  0.025992   
10         1.0  0.148539 -0.096910  0.257523  0.260881  0.312603  0.134134   
11         1.0  0.277948  0.091657  0.331656  0.307372  0.257359  0.065702   
12         1.0  0.106109 -0.025790  0.358875  0.297543  0.244335  0.016446   
13         1.0  0.126523 -0.040482  0.341129  0.381446  0.261154 -0.017049   
14         1.0  0.267687  0.099327  0.510454  0.511468  0.317788  0.067992   
15         1.0  0.137623 -0.085808  0.322446  0.344695  0.285642  0.056517   
16         1.0  0.263944  0.090358  0.368888  0.356645  0.252806  0.063921   
17         1.0  0.146299 -0.075174  0.291935  0.367094  0.268947  0.054049   
18         1.0  0.179298 -0.038306  0.319636  0.383029  0.275313  0.099083   
19         1.0  0.273218 -0.234703 -0.079620  0.159811  0.416406  0.368838   
20         1.0  0.196429  0.009021  0.317772  0.293484  0.185684  0.044063   
21         1.0  0.230999  0.135657  0.431966  0.403423  0.276571  0.060464   
22         1.0  0.145109 -0.035846  0.282707  0.291044  0.206862  0.048627   
23         1.0  0.235682  0.029241  0.349117  0.355932  0.290697  0.081008   
24         1.0  0.146944 -0.009583  0.352534  0.313435  0.197599  0.015352   
25         1.0  0.233512  0.067249  0.352310  0.316899  0.220584  0.044433   
26         1.0  0.172672 -0.037870  0.301100  0.303533  0.203767  0.017798   
27         1.0  0.198494  0.078718  0.478231  0.425219  0.257916  0.049410   
28         1.0  0.165998 -0.004175  0.289963  0.295084  0.224001  0.085586   
29         1.0  0.155225 -0.063337  0.231699  0.284514  0.219596  0.038581   
...        ...       ...       ...       ...       ...       ...       ...   
7165       1.0  0.132365  0.503936  0.271392 -0.042392  0.024487  0.080317   
7166       1.0  0.165383  0.408082  0.270187  0.015300  0.019000  0.025284   
7167       1.0  0.411916  0.322796  0.344183  0.333873  0.094867 -0.230982   
7168       1.0  0.404936  0.726247  0.167376 -0.169260  0.112154  0.050805   
7169       1.0  0.209224  0.625373  0.246565 -0.108078  0.174846  0.100347   
7170       1.0  0.242842  0.516606  0.263976 -0.040676  0.052257  0.055201   
7171       1.0  0.153789  0.522557  0.267617 -0.043499  0.034436  0.081305   
7172       1.0  0.266711  0.735734  0.233772 -0.075867  0.140193  0.080212   
7173       1.0  0.183156  0.506970  0.247162 -0.048503  0.041090  0.093071   
7174       1.0  0.197679  0.553775  0.269271 -0.056261  0.062528  0.061367   
7175       1.0 -0.673025 -0.279960  0.065945  0.086890  0.469024  0.088019   
7176       1.0 -0.574239 -0.258302  0.007644  0.078566  0.402132  0.093501   
7177       1.0 -0.515567 -0.219812  0.118473  0.106919  0.471155  0.121196   
7178       1.0 -0.614409 -0.261315  0.051138  0.062119  0.501500  0.096506   
7179       1.0 -0.578837 -0.331501  0.105921  0.089931  0.456617  0.079131   
7180       1.0 -0.528595 -0.208051  0.103669  0.086537  0.408476  0.069610   
7181       1.0 -0.442139 -0.328404  0.031452  0.056017  0.424856  0.073288   
7182       1.0 -0.616029 -0.302357  0.063417  0.095671  0.439930  0.069414   
7183       1.0 -0.547168 -0.266780  0.056115  0.048947  0.423631  0.081924   
7184       1.0 -0.520958 -0.

In [169]:
np.reshape(Tanuran,(Tanuran.shape[0],1))

array([['AdenomeraAndre'],
       ['AdenomeraAndre'],
       ['AdenomeraAndre'],
       ..., 
       ['ScinaxRuber'],
       ['ScinaxRuber'],
       ['ScinaxRuber']], dtype=object)

In [187]:
len(np.unique(Tanuran))

10

In [200]:
names = list(df.axes[1])
data = df.as_matrix()
classes = np.unique(data[:,-1]).tolist()
classes.index("HylaMinuta")
Xanuran = data[:,:-1].astype(float)
Tanuran = data[:,-1].tolist()

for i, c in enumerate(Tanuran):
    Tanuran[i] = classes.index(c)
Tanuran = np.array(Tanuran)
Tanuran = np.reshape(Tanuran,(-1,1))
Xnames = names[:-1]
Tnames = names[-1:]

Xanuran

array([[  1.53e-01,  -1.06e-01,   2.01e-01, ...,   5.77e-02,   1.19e-01,
          1.40e-02],
       [  1.72e-01,  -9.90e-02,   2.68e-01, ...,   2.01e-02,   8.23e-02,
          2.91e-02],
       [  1.52e-01,  -8.30e-02,   2.87e-01, ...,  -2.51e-02,   9.91e-02,
          7.72e-02],
       ..., 
       [ -5.83e-01,  -3.43e-01,   2.95e-02, ...,   2.78e-02,  -5.31e-04,
         -8.04e-02],
       [ -5.19e-01,  -3.08e-01,  -4.92e-03, ...,   4.18e-02,  -2.79e-02,
         -9.69e-02],
       [ -5.09e-01,  -3.24e-01,   6.21e-02, ...,   3.16e-02,  -2.94e-02,
         -8.79e-02]])

In [194]:
Tanuran

array([[0],
       [0],
       [0],
       ..., 
       [9],
       [9],
       [9]])

In [177]:
Xanuran.shape, Tanuran.shape

((7195, 21), (7195, 1))

In [209]:
Xanuran[:2,:]

array([[ 0.15, -0.11,  0.2 ,  0.32,  0.26,  0.1 , -0.15, -0.17,  0.12,
         0.19, -0.08, -0.16,  0.08,  0.14, -0.02, -0.11, -0.08, -0.01,
         0.06,  0.12,  0.01],
       [ 0.17, -0.1 ,  0.27,  0.34,  0.27,  0.06, -0.22, -0.21,  0.17,
         0.27, -0.1 , -0.25,  0.02,  0.16,  0.01, -0.09, -0.06, -0.04,
         0.02,  0.08,  0.03]])

In [179]:
Tanuran[:2]

array([[0],
       [0]])

In [180]:
for i in range(10):
    print('{} samples in class {}'.format(np.sum(Tanuran==i), i))

672 samples in class 0
3478 samples in class 1
542 samples in class 2
310 samples in class 3
472 samples in class 4
1121 samples in class 5
270 samples in class 6
114 samples in class 7
68 samples in class 8
148 samples in class 9


In [214]:
results = trainNNs(Xanuran, Tanuran, 0.8, [0, 5, [5, 5]], 5, 100, classify=True)

In [215]:
summarize(results)

[[0, 0.030507296733842958, 0.035441278665740115, 3.209761142730713],
 [5, 0.035024322446143175, 0.044753300903405166, 7.202175140380859],
 [[5, 5], 0.043571924947880494, 0.054482279360667116, 8.477503061294556]]

In [216]:
bestNetwork(summarize(results))

[0, 0.030507296733842958, 0.035441278665740115, 3.209761142730713]

Now do an investigation like you did for the regression data. 

Test at least 10 different hidden layer structures. Then train another network with your best hidden layer structure on 0.8 of the data and use the trained network on the testing data (the remaining 0.2 of the date). 

Plot the predicted and actual `Species` for the testing data as an integer.  Discuss what you see.

## Grading

Download [A6grader.tar](http://www.cs.colostate.edu/~anderson/cs440/notebooks/A6grader.tar) and extract `A6grader.py` from it.

In [60]:
%run -i "A6grader.py"


Testing summarize([[[1,1], [1.2, 1.3, 1.4], [2.2, 2.3, 2.4], 0.5], [[2,2,2], [4.4, 4.3, 4.2], [6.5, 6.4, 6.3], 0.6]])

--- 10/10 points. Correctly returned [[[1, 1], 1.3, 2.3000000000000003, 0.5], [[2, 2, 2], 4.3, 6.3999999999999995, 0.6]]

Testing bestNetwork([[[1, 1], 1.3, 2.3, 0.5], [[2, 2, 2], 4.3, 1.3, 0.6]])

--- 10/10 points. Correctly returned [[2, 2, 2], 4.3, 1.3, 0.6]

X = np.random.uniform(-1, 1, (100, 3))
T = np.hstack(((X**2 - 0.2*X**3).sum(axis=1,keepdims=True),
               (np.sin(X)).sum(axis=1,keepdims=True)))
result = trainNNs(X, T, 0.7, [0, 5, 10, [20, 20]], 10, 100, False)

--- 20/20 points. Correct.

Testing bestNetwork(summarize(result))

--- 20/20 points. You correctly found that network [20, 20] is best.

A6 Execution Grade is 60/60

======================= The regression data set =======================

--- _/5 points. Read the data in energydata_complete.csv into variables Xenergy and Tenergy.

--- _/5 points. Train some networks by calling the NeuralNetw